# Generated by Django 4.2.4 on 2024-04-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nippo', '0008_nippomodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nippomodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='イメージ画像'),
        ),
    ]
